
doctrine_relation_visualizer:
    resource: "@DoctrineRelationVisualizerBundle/Controller/"
    type:     annotation
    prefix:   /

tbn_api_generator:
    resource: "@ApiGeneratorBundle/Resources/config/routing.yml"

